name: Junie
run-name: Junie run ${{ inputs.run_id }}

permissions:
  contents: write
  pull-requests: write
  packages: read

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "id of workflow process"
        required: true
      workflow_params:
        description: "stringified params"
        required: true

jobs:
  call-workflow-passing-data:
    uses: jetbrains-junie/junie-workflows/.github/workflows/ej-issue.yml@main
    with:
      workflow_params: ${{ inputs.workflow_params }}
      runs-on: "ubuntu-latest"  # Optional: Specify which runner to use
      junie_ide: "PhpStorm"  # Optional: Specify which IDE to use (IdeaUltimate or PhpStorm)
    secrets:
      JUNIE_SECRETS_JSON: ${{ secrets.JUNIE_SECRETS_JSON }}